### ISSUE TITLE
Error to download files

### ISSUE THREAD

**Issue by sbernesto** [mitodl/edx-sga#151]
Hi, 

I trying to download the files, commands sent me the following error:

The Studio servers encountered an error
An error occurred in Studio and the page could not be loaded. Please try again in a few moments. We've logged the error and our staff is currently working to resolve this error as soon as possible. If the problem persists, please email us at

When I see the log, I saw to try to remove the files from a nonexistent path

```
Jul 27 12:39:57 openedx [service_variant=cms][django.request][env:sandbox] ERROR [openedx  8159] [base.py:256] - Internal Server Error: /preview/xblock/block-v1:edX+DemoX+Demo_Course+type@edx_sga+block@c8c0d0d4d2c3464580891f30bcba6430/handler/staff_download
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 64, in preview_handler
    resp = instance.handle(handler, req, suffix)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/mixins.py", line 89, in handle
    return self.runtime.handle(self, handler_name, request, suffix)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1277, in handle
    return super(MetricsMixin, self).handle(block, handler_name, request, suffix=suffix)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 1025, in handle
    results = handler(request, suffix)
  File "/edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/sga.py", line 393, in staff_download
    return self.download(path, answer['mimetype'], answer['filename'])
  File "/edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/sga.py", line 412, in download
    file = default_storage.open(path)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 37, in open
    return self._open(name, mode)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 201, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/edx/app/edxapp/edx-platform/edX/DemoX/edx_sga/c8c0d0d4d2c3464580891f30bcba6430/01459ea14f9e3b4496c27f7e2651f30ad598c709.doc'
```

The configuration I have, to save the files locally add the line is MEDIA_ROOT = '/edx/var/edxapp/uploads', the file aws.py lms

**Comment by pdpinch** [comment]
Something doesn't seem to be configured properly... 

What version of open edX are you using (named release? devstack or fullstack?) and what version of edx_sga?

Also, what is your setting for DEFAULT_FILE_STORAGE ?

**Comment by sbernesto** [comment]
Version dogwood.3, Native Open edX Ubuntu 12.04 64 bit Installation, and my aws.py, version edx_sga is the default of dogwood

```
if AUTH_TOKENS.get('DEFAULT_FILE_STORAGE'):
    DEFAULT_FILE_STORAGE = AUTH_TOKENS.get('DEFAULT_FILE_STORAGE')
elif AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_ROOT = '/edx/var/edxapp/uploads'
```

**Comment by pdpinch** [comment]
Yikes, this has been open since 2016. I assume it's been resolved by now.
