### ISSUE TITLE
Download all submissions returns 500 with `Object of type BlockUsageLocator is not JSON serializable`

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#195]
Testing on our QA stack at https://mitx-qa-next.mitx.mit.edu/courses/course-v1:DevOps+0.001_2+2018_Spring/courseware/4695c7a6558c4e839c4bfd2e80ae810b/a7cf01e88f434f19902033c811d1b469/?activate_block_id=block-v1%3ADevOps%2B0.001_2%2B2018_Spring%2Btype%40sequential%2Bblock%40a7cf01e88f434f19902033c811d1b469

Here's the stack trace:

```
Internal Server Error: /courses/course-v1:DevOps+0.001_2+2018_Spring/xblock/block-v1:DevOps+0.001_2+2018_Spring+type@edx_sga+block@test-sgap1/handler/prepare_download_submissions
Traceback (most recent call last):
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
   return func(*args, **kwargs)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 877, in handle_xblock_callback
   return _invoke_xblock_handler(request, course_id, usage_id, handler, suffix, course=course)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 982, in _invoke_xblock_handler
   resp = instance.handle(handler, req, suffix)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/mixins.py", line 89, in handle
   return self.runtime.handle(self, handler_name, request, suffix)
 File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1339, in handle
   return super(MetricsMixin, self).handle(block, handler_name, request, suffix=suffix)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 1029, in handle
   results = handler(request, suffix)
 File "/edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/sga.py", line 769, in prepare_download_submissions
   user
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
   return self.apply_async(args, kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
   **dict(self._get_exec_options(), **options)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
   reply_to=reply_to or self.oid, **options
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
   **kwargs
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/kombu/messaging.py", line 165, in publish
   compression, headers)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/kombu/messaging.py", line 241, in _prepare
   body) = dumps(body, serializer=serializer)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/kombu/serialization.py", line 164, in dumps
   payload = encoder(data)
 File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
   self.gen.throw(type, value, traceback)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/kombu/serialization.py", line 59, in _reraise_errors
   reraise(wrapper, wrapper(exc), sys.exc_info()[2])
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/kombu/serialization.py", line 55, in _reraise_errors
   yield
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/kombu/serialization.py", line 164, in dumps
   payload = encoder(data)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/anyjson/__init__.py", line 141, in dumps
   return implementation.dumps(value)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/anyjson/__init__.py", line 87, in dumps
   return self._encode(data)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/simplejson/__init__.py", line 382, in dumps
   return _default_encoder.encode(obj)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/simplejson/encoder.py", line 291, in encode
   chunks = self.iterencode(o, _one_shot=True)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/simplejson/encoder.py", line 373, in iterencode
   return _iterencode(o, 0)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/simplejson/encoder.py", line 268, in default
   o.__class__.__name__)
EncodeError: Object of type BlockUsageLocator is not JSON serializable
```

**Comment by amir-qayyum-khan** [comment]
please make it unicode @gsidebo 

```zip_student_submissions.delay(
                self.block_course_id,
                unicode(self.block_id),
                self.location,
                user
            )```

**Comment by gsidebo** [comment]
I have a fix in progress
