### ISSUE TITLE
ModuleNotFoundError: No module named 'openedx.core.lib.safe_lxml'

### ISSUE THREAD

**Issue by lpm0073** [mitodl/edx-sga#330]
running into this exception on a newly built Nutmeg platform that has courses that use edx-sga. have you seen this before. 
By the way: i noticed in the edx-platform that common.lib.safe_lxml.safe.lxml.etree.py, the imports to lxml.etree are broken, suggesting that perhaps this requirements has been removed in nutmet? not sure, but it seems ominous. 

<img width="1282" alt="Screen Shot 2022-10-05 at 13 12 58" src="https://user-images.githubusercontent.com/1178819/194132110-9a33ab48-1229-48ab-a718-17ac6e3e15a1.png">

`2022-10-05 18:09:15,692 ERROR 12 [django.request] [user 8] [ip 192.168.4.74] log.py:224 - Internal Server Error: /course/course-v1:GCA+CEa+0_0en_0dr_QQ_220708a
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/pyenv/versions/3.8.12/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/openedx/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/course.py", line 293, in course_handler
    return course_index(request, CourseKey.from_string(course_key_string))
  File "/openedx/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/openedx/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/course.py", line 681, in course_index
    course_structure = _course_outline_json(request, course_module)
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/course.py", line 362, in _course_outline_json
    return create_xblock_info(
  File "/openedx/venv/lib/python3.8/site-packages/edx_django_utils/plugins/pluggable_override.py", line 77, in wrapper
    return prev_fn(*args, **kwargs)
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1175, in create_xblock_info
    child_info = _create_xblock_child_info(
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1540, in _create_xblock_child_info
    child_info['children'] = [
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1541, in <listcomp>
    create_xblock_info(
  File "/openedx/venv/lib/python3.8/site-packages/edx_django_utils/plugins/pluggable_override.py", line 77, in wrapper
    return prev_fn(*args, **kwargs)
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1175, in create_xblock_info
    child_info = _create_xblock_child_info(
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1540, in _create_xblock_child_info
    child_info['children'] = [
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1541, in <listcomp>
    create_xblock_info(
  File "/openedx/venv/lib/python3.8/site-packages/edx_django_utils/plugins/pluggable_override.py", line 77, in wrapper
    return prev_fn(*args, **kwargs)
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1175, in create_xblock_info
    child_info = _create_xblock_child_info(
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1540, in _create_xblock_child_info
    child_info['children'] = [
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1541, in <listcomp>
    create_xblock_info(
  File "/openedx/venv/lib/python3.8/site-packages/edx_django_utils/plugins/pluggable_override.py", line 77, in wrapper
    return prev_fn(*args, **kwargs)
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/views/item.py", line 1359, in create_xblock_info
    xblock_info['has_partition_group_components'] = has_children_visible_to_specific_partition_groups(
  File "/openedx/edx-platform/./cms/djangoapps/contentstore/utils.py", line 254, in has_children_visible_to_specific_partition_groups
    for child in xblock.get_children():
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 560, in get_children
    in super().get_children(usage_id_filter)
  File "/openedx/venv/lib/python3.8/site-packages/xblock/mixins.py", line 400, in get_children
    return [
  File "/openedx/venv/lib/python3.8/site-packages/xblock/mixins.py", line 401, in <listcomp>
    self.get_child(usage_id)
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 570, in get_child
    child = super().get_child(usage_id)
  File "/openedx/venv/lib/python3.8/site-packages/xblock/mixins.py", line 389, in get_child
    child_block = self.runtime.get_block(usage_id, for_parent=self)
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1529, in get_block
    return self.load_item(usage_id, for_parent=for_parent)
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py", line 120, in _load_item
    class_ = self.load_block_type(block_data.block_type)
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1537, in load_block_type
    return super().load_block_type(block_type)
  File "/openedx/venv/lib/python3.8/site-packages/xblock/runtime.py", line 621, in load_block_type
    return XBlock.load_class(block_type, self.default_class, self.select)
  File "/openedx/venv/lib/python3.8/site-packages/xblock/plugin.py", line 115, in load_class
    PLUGIN_CACHE[key] = cls._load_class_entry_point(selected_entry_point)
  File "/openedx/venv/lib/python3.8/site-packages/xblock/plugin.py", line 70, in _load_class_entry_point
    class_ = entry_point.load()
  File "/openedx/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/openedx/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/openedx/requirements/edx-sga/edx_sga/sga.py", line 28, in <module>
    from openedx.core.lib.safe_lxml import etree
ModuleNotFoundError: No module named 'openedx.core.lib.safe_lxml'
`

**Comment by isankadn** [comment]
it seems in the Nutmeg and other previous versions this "safe_lxml" is available here `https://github.com/openedx/edx-platform/tree/open-release/nutmeg.master/common/lib/safe_lxml/safe_lxml`.  ` "common.lib.safe_lxml"`

**Comment by lpm0073** [comment]
This has since been resolved. thanks.
