### ISSUE TITLE
DatabaseNotReadyError()'

### ISSUE THREAD

**Issue by VladimirAndropov** [mitodl/edx-sga#342]
## Expected Behavior
When runing Task lms.djangoapps.grades.tasks.recalculate_subsection_grade_v3 for grades from edx_sga, raised exception: '
DatabaseNotReadyError()

## Possible Solution
maybe problem in cyrillic simbols in students filenames or answers

## Additional Details
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/grades/tasks.py", line 169, in recalculate_subsection_grade_v3
    _recalculate_subsection_grade(self, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/grades/tasks.py", line 233, in _recalculate_subsection_grade
    raise self.retry(kwargs=kwargs, exc=exc)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/task.py", line 684, in retry
    maybe_reraise()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 248, in maybe_reraise
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/grades/tasks.py", line 217, in _recalculate_subsection_grade
    raise DatabaseNotReadyError
DatabaseNotReadyError

**Comment by Anas12091101** [comment]
https://github.com/openedx/edx-platform/pull/35390 has been merged. @arslanashraf7, @pdpinch we can now close this issue.
